[package]
name = "euclid"
version = "0.1.0"
authors = ["Ray Jaffer <ray@thelondonvandal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"ansi_term" = "0.12.1"
"clap" = "*"
sdl2 = "0.31.0"
gl = "0.10.0"